import type { NewsArticle } from '@/types/news';

export const newsList: NewsArticle[] = [
  {
    id: '1',
    articleTitle: 'New Marriage Support Fund Announced for 2026',
    category: 'Policy',
    language: 'English',
    publishedDate: '2026-07-28',
    updatedDate: '2026-07-28',
    status: 'Published',
  },
  {
    id: '2',
    articleTitle: 'الإعلان عن مبادرات جديدة للزواج في الإمارات',
    category: 'Initiative',
    language: 'Arabic',
    publishedDate: '2026-07-27',
    updatedDate: '2026-07-27',
    status: 'Published',
  },
  {
    id: '3',
    articleTitle: 'Family Counseling Services Expanded to All Emirates',
    category: 'Service',
    language: 'English',
    publishedDate: '2026-07-26',
    updatedDate: '2026-07-27',
    status: 'Published',
  },
  {
    id: '4',
    articleTitle: 'Housing Subsidy Program Opens New Application Window',
    category: 'Policy',
    language: 'English',
    publishedDate: '2026-07-25',
    updatedDate: '2026-07-26',
    status: 'Draft',
  },
  {
    id: '5',
    articleTitle: 'Workshop Series on Effective Communication in Marriage',
    category: 'Education',
    language: 'English',
    publishedDate: '2026-07-24',
    updatedDate: '2026-07-24',
    status: 'Published',
  },
  {
    id: '6',
    articleTitle: 'Dubai Launches New Marriage Grant Program',
    category: 'Initiative',
    language: 'English',
    publishedDate: '2026-07-23',
    updatedDate: '2026-07-24',
    status: 'Published',
  },
  {
    id: '7',
    articleTitle: 'سلسلة ورش العمل للتوعية الأسرية',
    category: 'Education',
    language: 'Arabic',
    publishedDate: '2026-07-22',
    updatedDate: '2026-07-23',
    status: 'Draft',
  },
  {
    id: '8',
    articleTitle: 'Abu Dhabi Marriage Fund Reports Record Applications',
    category: 'News',
    language: 'English',
    publishedDate: '2026-07-21',
    updatedDate: '2026-07-22',
    status: 'Published',
  },
  {
    id: '9',
    articleTitle: 'Pre-Marital Screening Now Available Online',
    category: 'Health',
    language: 'English',
    publishedDate: '2026-07-20',
    updatedDate: '2026-07-21',
    status: 'Pending',
  },
  {
    id: '10',
    articleTitle: 'دليل التخطيط المالي للمتزوجين الجدد',
    category: 'Finance',
    language: 'Arabic',
    publishedDate: '2026-07-19',
    updatedDate: '2026-07-19',
    status: 'Published',
  },
  {
    id: '11',
    articleTitle: 'Sharjah Cultural Office Hosts Family Forum',
    category: 'Culture',
    language: 'English',
    publishedDate: '2026-07-18',
    updatedDate: '2026-07-19',
    status: 'Published',
  },
  {
    id: '12',
    articleTitle: 'New Regulations for Marriage Consultants Issued',
    category: 'Policy',
    language: 'English',
    publishedDate: '2026-07-17',
    updatedDate: '2026-07-18',
    status: 'Draft',
  },
  {
    id: '13',
    articleTitle: 'تحديث منصة الزواج الإلكترونية',
    category: 'Service',
    language: 'Arabic',
    publishedDate: '2026-07-16',
    updatedDate: '2026-07-17',
    status: 'Published',
  },
];
