export interface Consultation {
  id: string;
  sessionTitle: string;
  sessionType: string;
  emirates: string;
  date: string;
  status: 'Published' | 'Draft' | 'Pending';
  slug?: string;
  sessionTitleAr?: string;
  category?: string;
  maritalStage?: string;
  language?: string;
  publishedDate?: string;
  startTime?: string;
  endTime?: string;
  duration?: string;
  timeZone?: string;
  meetingFormat?: string;
  sessionLink?: string;
  maxParticipants?: number;
  isFree?: boolean;
  fee?: number;
  processingFee?: number;
  discount?: number;
  counselor?: string;
  counselorPhoto?: string;
  counselorTitle?: string;
  counselorBio?: string;
  learnMore?: Record<string, unknown>;
  gallery?: string[];
  coverImage?: string;
  description?: string;
  objectives?: string[];
  whatYouWillLearn?: string[];
  whoShouldAttend?: string[];
  schedule?: Record<string, unknown>;
  bookingNotice?: string;
  showDoctor?: boolean;
  showLearnMore?: boolean;
  showGallery?: boolean;
  showSchedule?: boolean;
  showBooking?: boolean;
  isBookable?: boolean;
}