export interface Initiative {
  id: string;
  title: string;
  category: string;
  emirates: string;
  startDate: string;
  endDate: string;
  status: 'Published' | 'Draft' | 'Pending';
  isFeatured?: boolean;
  isListed?: boolean;
  slug?: string;
  titleAr?: string;
  subtitle?: string;
  subtitleAr?: string;
  description?: string;
  descriptionAr?: string;
  purpose?: string;
  purposeAr?: string;
  objectives?: string[];
  objectivesAr?: string[];
  basicInformation?: string[];
  basicInformationAr?: string[];
  supportOffered?: Record<string, boolean>;
  benefits?: string[];
  benefitsAr?: string[];
  coverImage?: string;
  badge?: string;
  badgeAr?: string;
  contact?: string[];
  contactAr?: string[];
  officialWebsiteUrl?: string;
  shareUrl?: string;
  showAbout?: boolean;
  showSupportOffered?: boolean;
  showBenefits?: boolean;
  showApplicationForm?: boolean;
}